os: linux
dist: focal
language: c
compiler: gcc

addons:
  apt:
    packages:
      - appstream
      - clang
      - clang-format
      - libinih-dev
      - libdbus-1-dev
      - libsystemd-dev
      - meson
  artifacts:
    paths:
    - $(git ls-files -o | tr "\n" ":")

script:
  - ./scripts/format-check.sh
  - ./bootstrap.sh -Dwith-examples=true
  - meson test -C builddir
  - dbus-run-session -- gamemode-simulate-game
  - ./scripts/static-analyser-check.sh 
